# Generated by Django 4.2.8 on 2023-12-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='version',
            field=models.CharField(default='2023_1224', max_length=50),
        ),
    ]
